"use client";
import { useRef, useEffect, useCallback, useState } from "react";
import { PanelFrame } from "@/components/shared/PanelFrame";
import type { StateVector, Telemetry } from "@/lib/types";
import { getGroundTrackLabel } from "@/lib/ground-track";
import { getLunarGroundTrackLabel } from "@/lib/lunar-ground-track";
import { useLocale } from "@/context/LocaleContext";
import { useMetContext } from "@/context/MetContext";
import {
  REFERENCE_TRAJECTORY,
  PROJECTION_COS,
  PROJECTION_SIN,
  MOON_DIST_KM,
} from "@/data/reference-trajectory";

interface OrbitMapPanelProps {
  stateVector: StateVector | null;
  moonPosition: { x: number; y: number; z: number } | null;
  metMs: number;
  telemetry: Telemetry | null;
}

/** Stored path point in km (J2000 geocentric X, Y). */
interface PathPoint {
  x: number;
  y: number;
}

// REFERENCE_TRAJECTORY is imported from src/data/reference-trajectory.ts,
// which is generated by scripts/build-reference-trajectory.mjs from real
// Artemis II state vectors (JPL Horizons for the trans-lunar coast +
// NASA/JSC/FOD/FDO Artemis II OEM for the flyby/return). No synthetic data.
//
// Frame: EME2000 X-Y plane (looking down the celestial north / J2000 +Z),
// rotated about +Z so the Earth → Moon (at closest approach) axis lies
// along +X. Coordinates are normalized by |Moon_xy| at closest approach
// (~360,000 km, exported as MOON_DIST_KM), so the Moon sits at exactly
// (1, 0), Earth is at (0, 0), and the spacecraft apogee sits at ~(1.02, 0)
// — just past the Moon, consistent with a far-side free-return flyby.
// The Z component is dropped — in this top-down view the curve sweeps
// only ~±15,000 km off the Earth-Moon line.
//
// PROJECTION_COS / PROJECTION_SIN define the same rotation, so the panel
// can apply it to live JPL Horizons telemetry below and have the orion dot
// land exactly on the drawn curve.

const WAYPOINTS = [
  { label: "TLI", metMs: (25 * 3600 + 8 * 60 + 42) * 1000, align: "center" as const, offsetX: 0, offsetY: -10 },
  { label: "Closest Approach", metMs: (5 * 24 * 3600 + 30 * 60) * 1000, align: "right" as const, offsetX: 22, offsetY: -36 },
  { label: "~6,513 km", distKm: 6513, metMs: (5 * 24 * 3600 + 30 * 60) * 1000, align: "right" as const, offsetX: 22, offsetY: -24 },
];

function generateStars(count: number): { x: number; y: number; r: number; a: number }[] {
  const stars: { x: number; y: number; r: number; a: number }[] = [];
  let seed = 42;
  function rand(): number {
    seed |= 0; seed = (seed + 0x6D2B79F5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  }
  for (let i = 0; i < count; i++) {
    stars.push({
      x: rand(),
      y: rand(),
      r: 0.3 + rand() * 0.7,
      a: 0.15 + rand() * 0.45,
    });
  }
  return stars;
}

const STARS = generateStars(200);

/** Maximum number of path-history points to keep. */
const MAX_PATH_POINTS = 500;

/** Format a number with commas: 12345 -> "12,345" */
function fmtKm(km: number): string {
  return Math.round(km).toLocaleString("en-US");
}

/** Convert km to the user's selected distance unit and format */
function fmtDistCanvas(km: number, unit: string): string {
  switch (unit) {
    case "mph": return `${Math.round(km * 0.621371).toLocaleString("en-US")} mi`;
    case "kn":  return `${Math.round(km * 0.539957).toLocaleString("en-US")} nmi`;
    default:    return `${fmtKm(km)} km`;
  }
}

function distUnitLabel(unit: string): string {
  switch (unit) {
    case "mph": return "mi";
    case "kn":  return "nmi";
    default:    return "km";
  }
}

export function OrbitMapPanel({ stateVector, moonPosition, metMs, telemetry }: OrbitMapPanelProps) {
  const { t } = useLocale();
  const { speedUnit } = useMetContext();
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const insetRef = useRef<HTMLCanvasElement>(null);
  const earthInsetRef = useRef<HTMLCanvasElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const rafRef = useRef<number | null>(null);
  const [showInset, setShowInset] = useState(false);
  const [showEarthInset, setShowEarthInset] = useState(false);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [realScale, setRealScale] = useState(false);
  // Trail of recent Orion-relative-to-Moon positions, for the zoom inset.
  const insetTrailRef = useRef<Array<{ relX: number; relY: number; metMs: number }>>([]);
  // Trail for Earth inset
  const earthInsetTrailRef = useRef<Array<{ x: number; y: number; metMs: number }>>([]);

  // Store unit in a ref for use inside the draw callback
  const unitRef = useRef(speedUnit);
  unitRef.current = speedUnit;

  // Store translated inset labels in a ref for use inside the draw callback
  const insetLabelsRef = useRef({ moonDetail: "MOON DETAIL", earthDetail: "EARTH DETAIL", kmView: "km view" });
  insetLabelsRef.current = {
    moonDetail: t("orbitMap.moonDetail").toUpperCase(),
    earthDetail: "EARTH DETAIL",
    kmView: t("orbitMap.kmView"),
  };

  // Auto-enable Moon inset when within 60,000 km
  useEffect(() => {
    if (telemetry && telemetry.moonDistKm < 60000) {
      setShowInset(true);
    }
  }, [telemetry?.moonDistKm != null && telemetry.moonDistKm < 60000]);

  // Auto-enable Earth inset when within 60,000 km of Earth (re-entry approach)
  useEffect(() => {
    if (telemetry && telemetry.earthDistKm < 60000) {
      setShowEarthInset(true);
    }
  }, [telemetry?.earthDistKm != null && telemetry.earthDistKm < 60000]);


  const draw = useCallback(() => {
    const canvas = canvasRef.current;
    const container = containerRef.current;
    if (!canvas || !container) return;

    const dpr = window.devicePixelRatio || 1;
    const w = container.clientWidth;
    const h = container.clientHeight;

    if (canvas.width !== w * dpr || canvas.height !== h * dpr) {
      canvas.width = w * dpr;
      canvas.height = h * dpr;
      canvas.style.width = `${w}px`;
      canvas.style.height = `${h}px`;
    }

    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    ctx.clearRect(0, 0, w, h);

    // Background
    ctx.fillStyle = "#060b14";
    ctx.fillRect(0, 0, w, h);

    // Starfield
    for (const star of STARS) {
      ctx.beginPath();
      ctx.arc(star.x * w, star.y * h, star.r, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(255,255,255,${star.a})`;
      ctx.fill();
    }

    // ---- Fixed-scale layout ----
    // Earth at left-center, Moon at right-center. The Moon is anchored to
    // its position at closest approach (~MOON_DIST_KM ≈ 360,000 km from
    // Earth in the EME2000 X-Y plane), not its live position, so the
    // reference trajectory always lines up with both bodies.
    const earthPx = { x: w * 0.12, y: h * 0.52 };
    const moonPx = { x: w * 0.88, y: h * 0.52 };
    const trackWidth = moonPx.x - earthPx.x; // pixels between Earth and Moon
    const pixelsPerKm = trackWidth / MOON_DIST_KM;

    // Helper: km coords (Earth = 0,0) -> canvas pixels.  Y+ = up (flip for canvas)
    function kmToCanvas(xKm: number, yKm: number): { x: number; y: number } {
      return {
        x: earthPx.x + xKm * pixelsPerKm,
        y: earthPx.y - yKm * pixelsPerKm, // flip Y
      };
    }

    // Helper: normalized coords (Earth=0,0  Moon=1,0  Y+=up) -> canvas pixels
    function toCanvas(nx: number, ny: number): { x: number; y: number } {
      return kmToCanvas(nx * MOON_DIST_KM, ny * MOON_DIST_KM);
    }

    // --- Distance label between Earth and Moon ---
    ctx.save();
    ctx.font = "9px monospace";
    ctx.fillStyle = "rgba(100,160,255,0.25)";
    ctx.textAlign = "center";
    const midX = (earthPx.x + moonPx.x) / 2;
    ctx.fillText(fmtDistCanvas(MOON_DIST_KM, unitRef.current), midX, earthPx.y + 4);
    ctx.restore();

    // --- FREE-RETURN TRAJECTORY subtitle ---
    ctx.save();
    ctx.font = "bold 8px monospace";
    ctx.fillStyle = "rgba(0,220,255,0.55)";
    ctx.textAlign = "center";
    ctx.fillText("FREE-RETURN TRAJECTORY", w / 2, h - 8);
    ctx.restore();

    // Trajectory paths and waypoints are drawn LATER (after the Earth and
    // Moon graphics) so the curve sits on top of both bodies rather than
    // being occluded by them. `splitIdx` and `lastPastPt` are produced down
    // there and consumed by the Orion-position code further below.
    let splitIdx = 0;
    let lastPastPt: { x: number; y: number } | null = null;

    // --- Earth ---
    // Real scale: Earth radius 6,371 km, Moon radius 1,737 km
    const earthR = realScale
      ? Math.max(4, 6371 * pixelsPerKm)
      : Math.max(6, Math.min(w, h) * 0.03);
    const earthGrad = ctx.createRadialGradient(
      earthPx.x - earthR * 0.3, earthPx.y - earthR * 0.3, 0,
      earthPx.x, earthPx.y, earthR
    );
    earthGrad.addColorStop(0, "#6ab4ff");
    earthGrad.addColorStop(0.5, "#1a6bb5");
    earthGrad.addColorStop(1, "#0a2a50");

    // Glow
    ctx.save();
    const earthGlow = ctx.createRadialGradient(earthPx.x, earthPx.y, earthR * 0.8, earthPx.x, earthPx.y, earthR * 2.2);
    earthGlow.addColorStop(0, "rgba(30,100,200,0.18)");
    earthGlow.addColorStop(1, "rgba(30,100,200,0)");
    ctx.beginPath();
    ctx.arc(earthPx.x, earthPx.y, earthR * 2.2, 0, Math.PI * 2);
    ctx.fillStyle = earthGlow;
    ctx.fill();
    ctx.restore();

    ctx.save();
    ctx.beginPath();
    ctx.arc(earthPx.x, earthPx.y, earthR, 0, Math.PI * 2);
    ctx.fillStyle = earthGrad;
    ctx.fill();
    ctx.restore();

    // Earth label
    ctx.save();
    ctx.font = "bold 10px monospace";
    ctx.fillStyle = "rgba(100,180,255,0.85)";
    ctx.textAlign = "center";
    // Earth/Moon body labels are pushed down to ~3/4 of canvas height —
    // roughly halfway between the planet center (h*0.52) and the bottom
    // edge — so they stay clear of the clustered Orion / Closest Approach
    // labels near apogee.
    ctx.fillText("Earth", earthPx.x, h * 0.77);
    ctx.restore();

    // --- Day/Night terminator ---
    // Sun direction determines which half of Earth is lit.
    // Approximate: sun longitude moves ~15°/hour, at equinox the terminator is a vertical line.
    const utcNow = Date.now();
    const hourOfDay = ((utcNow % 86400000) / 3600000); // 0-24
    // Sun is at local noon at longitude = (12 - hourOfDay) * 15 degrees
    // Terminator angle relative to Earth on our map (viewed from above ecliptic pole)
    const sunAngle = ((12 - hourOfDay) * 15 - 90) * Math.PI / 180;

    ctx.save();
    ctx.beginPath();
    // Draw a half-circle on the night side
    ctx.arc(earthPx.x, earthPx.y, earthR + 1, sunAngle, sunAngle + Math.PI);
    ctx.fillStyle = "rgba(0,0,0,0.45)";
    ctx.fill();
    ctx.restore();

    // --- Lunar gravity contours ---
    // Draw concentric rings around the Moon showing gravitational influence.
    // Lunar Hill sphere ≈ 61,500 km — the region where Moon's gravity dominates.
    const LUNAR_HILL_SPHERE_KM = 61500;
    const hillPx = LUNAR_HILL_SPHERE_KM * pixelsPerKm;

    // Gravity contour rings at various distances (km from Moon center)
    const gravityRings = [
      { radiusKm: 10000, opacity: 0.12, label: "" },
      { radiusKm: 20000, opacity: 0.09, label: "" },
      { radiusKm: 35000, opacity: 0.06, label: "" },
      { radiusKm: LUNAR_HILL_SPHERE_KM, opacity: 0.10, label: "Hill Sphere" },
    ];

    for (const ring of gravityRings) {
      const rPx = ring.radiusKm * pixelsPerKm;
      if (rPx < 3) continue; // too small to render

      ctx.save();
      ctx.beginPath();
      ctx.arc(moonPx.x, moonPx.y, rPx, 0, Math.PI * 2);
      ctx.strokeStyle = `rgba(180, 190, 210, ${ring.opacity})`;
      ctx.lineWidth = ring.radiusKm === LUNAR_HILL_SPHERE_KM ? 1.2 : 0.6;
      if (ring.radiusKm === LUNAR_HILL_SPHERE_KM) {
        ctx.setLineDash([4, 6]);
      }
      ctx.stroke();
      ctx.restore();

      // Label for Hill sphere
      if (ring.label && rPx > 20) {
        ctx.save();
        ctx.font = "7px monospace";
        ctx.fillStyle = `rgba(180, 190, 210, 0.35)`;
        ctx.textAlign = "center";
        ctx.fillText(ring.label, moonPx.x, moonPx.y - rPx - 3);
        ctx.restore();
      }
    }

    // Subtle radial gradient showing gravity well
    ctx.save();
    const gravGrad = ctx.createRadialGradient(
      moonPx.x, moonPx.y, 0,
      moonPx.x, moonPx.y, hillPx
    );
    gravGrad.addColorStop(0, "rgba(140, 160, 200, 0.06)");
    gravGrad.addColorStop(0.3, "rgba(140, 160, 200, 0.03)");
    gravGrad.addColorStop(1, "rgba(140, 160, 200, 0)");
    ctx.beginPath();
    ctx.arc(moonPx.x, moonPx.y, hillPx, 0, Math.PI * 2);
    ctx.fillStyle = gravGrad;
    ctx.fill();
    ctx.restore();

    // Also show Earth's gravity influence as a subtle gradient
    ctx.save();
    const earthGravR = w * 0.35; // visual representation, not to scale
    const earthGravGrad = ctx.createRadialGradient(
      earthPx.x, earthPx.y, 0,
      earthPx.x, earthPx.y, earthGravR
    );
    earthGravGrad.addColorStop(0, "rgba(80, 140, 255, 0.04)");
    earthGravGrad.addColorStop(0.5, "rgba(80, 140, 255, 0.015)");
    earthGravGrad.addColorStop(1, "rgba(80, 140, 255, 0)");
    ctx.beginPath();
    ctx.arc(earthPx.x, earthPx.y, earthGravR, 0, Math.PI * 2);
    ctx.fillStyle = earthGravGrad;
    ctx.fill();
    ctx.restore();

    // --- Moon ---
    const moonR = realScale
      ? Math.max(2, 1737 * pixelsPerKm)
      : Math.max(3, Math.min(w, h) * 0.015);
    const moonGrad = ctx.createRadialGradient(
      moonPx.x - moonR * 0.25, moonPx.y - moonR * 0.25, 0,
      moonPx.x, moonPx.y, moonR
    );
    moonGrad.addColorStop(0, "#d0d4d8");
    moonGrad.addColorStop(0.6, "#8a8e92");
    moonGrad.addColorStop(1, "#3a3e42");

    ctx.save();
    ctx.beginPath();
    ctx.arc(moonPx.x, moonPx.y, moonR, 0, Math.PI * 2);
    ctx.fillStyle = moonGrad;
    ctx.fill();
    ctx.restore();

    // Moon label
    ctx.save();
    ctx.font = "bold 10px monospace";
    ctx.fillStyle = "rgba(180,185,190,0.85)";
    ctx.textAlign = "center";
    ctx.fillText("Moon", moonPx.x, h * 0.77);
    ctx.font = "9px monospace";
    ctx.fillStyle = "rgba(180,185,190,0.65)";
    ctx.fillText("(at closest approach)", moonPx.x, h * 0.77 + 12);
    ctx.restore();

    // --- Reference trajectory (drawn on top of Earth and Moon) ---
    // Find where Orion is on the reference trajectory by MET. MET is
    // monotonic across every phase of the curve, so the array index it
    // selects is always a valid split point between past and future arcs.
    // (An earlier version also tried to advance the split using
    // earthDistKm/MOON_DIST_KM matched against point.x, but x is only
    // monotonic on the outbound arc — on the flyby loop and return arc
    // most points satisfy x <= frac, which leaked the split into the
    // return arc and produced visible kinks in the drawn trajectory.)
    for (let i = 0; i < REFERENCE_TRAJECTORY.length; i++) {
      if (REFERENCE_TRAJECTORY[i].metMs <= metMs) {
        splitIdx = i;
      }
    }

    // Draw past path (solid, cyan) — up to Orion's actual position
    if (splitIdx > 0) {
      ctx.save();
      ctx.setLineDash([]);
      ctx.strokeStyle = "rgba(0,220,255,0.4)";
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      const first = toCanvas(REFERENCE_TRAJECTORY[0].x, REFERENCE_TRAJECTORY[0].y);
      ctx.moveTo(first.x, first.y);
      for (let i = 1; i <= Math.min(splitIdx, REFERENCE_TRAJECTORY.length - 1); i++) {
        const p = toCanvas(REFERENCE_TRAJECTORY[i].x, REFERENCE_TRAJECTORY[i].y);
        ctx.lineTo(p.x, p.y);
        lastPastPt = p;
      }
      ctx.stroke();
      ctx.restore();
    }

    // Draw future path (dashed, faint) — from Orion's position onward
    if (splitIdx < REFERENCE_TRAJECTORY.length - 1) {
      ctx.save();
      ctx.setLineDash([8, 12]);
      ctx.strokeStyle = "rgba(0,220,255,0.18)";
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      const sf = toCanvas(REFERENCE_TRAJECTORY[splitIdx].x, REFERENCE_TRAJECTORY[splitIdx].y);
      ctx.moveTo(sf.x, sf.y);
      for (let i = splitIdx + 1; i < REFERENCE_TRAJECTORY.length; i++) {
        const p = toCanvas(REFERENCE_TRAJECTORY[i].x, REFERENCE_TRAJECTORY[i].y);
        ctx.lineTo(p.x, p.y);
      }
      ctx.stroke();
      ctx.restore();
    }

    // --- Waypoint labels ---
    const drawnDots = new Set<number>();
    for (const wp of WAYPOINTS) {
      let nearest = REFERENCE_TRAJECTORY[0];
      let minDiff = Infinity;
      for (const pt of REFERENCE_TRAJECTORY) {
        const diff = Math.abs(pt.metMs - wp.metMs);
        if (diff < minDiff) {
          minDiff = diff;
          nearest = pt;
        }
      }
      const passed = metMs >= wp.metMs;
      const p = toCanvas(nearest.x, nearest.y);

      if (!drawnDots.has(wp.metMs)) {
        drawnDots.add(wp.metMs);
        ctx.save();
        ctx.beginPath();
        ctx.arc(p.x, p.y, 3, 0, Math.PI * 2);
        // Dot color matches the waypoint label color (yellow) so the
        // association between the dot and its text is obvious even when
        // the label is offset away from the dot.
        ctx.fillStyle = passed ? "rgba(255,213,79,0.95)" : "rgba(255,213,79,0.6)";
        ctx.fill();
        ctx.restore();
      }

      ctx.save();
      ctx.font = "9px monospace";
      ctx.fillStyle = passed ? "rgba(255,213,79,0.9)" : "rgba(255,213,79,0.65)";
      ctx.textAlign = wp.align || "center";
      const offsetX = (wp as { offsetX?: number }).offsetX ?? (wp.align === "right" ? 8 : 0);
      const labelX = p.x + offsetX;
      const wpLabel = (wp as { distKm?: number }).distKm != null
        ? `~${fmtDistCanvas((wp as { distKm: number }).distKm, unitRef.current)}`
        : wp.label;
      ctx.fillText(wpLabel, labelX, p.y + (wp.offsetY || -8));
      ctx.restore();
    }

    // Splashdown zone removed — will be replaced with an Earth detail
    // zoom inset (like the Moon zoom) closer to re-entry.

    // --- Orion position ---
    // The reference trajectory is a static EME2000 projection rotated so the
    // Earth-apogee axis is +X. The same rotation is exported as
    // PROJECTION_COS / PROJECTION_SIN so we can apply it to live JPL Horizons
    // telemetry and the orion dot will sit exactly on the drawn curve.
    //
    // When telemetry is unavailable (cold start), fall back to a linear
    // MET interpolation along REFERENCE_TRAJECTORY so the dot still moves.
    let orionPx: { x: number; y: number };
    if (
      stateVector &&
      (stateVector.position.x !== 0 || stateVector.position.y !== 0)
    ) {
      const px = stateVector.position.x;
      const py = stateVector.position.y;
      const xn = ( px * PROJECTION_COS + py * PROJECTION_SIN) / MOON_DIST_KM;
      const yn = (-px * PROJECTION_SIN + py * PROJECTION_COS) / MOON_DIST_KM;
      orionPx = toCanvas(xn, yn);
    } else {
      let idxA = 0;
      for (let i = 0; i < REFERENCE_TRAJECTORY.length; i++) {
        if (REFERENCE_TRAJECTORY[i].metMs <= metMs) idxA = i;
      }
      const a = REFERENCE_TRAJECTORY[idxA];
      const b = REFERENCE_TRAJECTORY[Math.min(idxA + 1, REFERENCE_TRAJECTORY.length - 1)];
      const span = b.metMs - a.metMs;
      const t = span > 0 ? Math.max(0, Math.min(1, (metMs - a.metMs) / span)) : 0;
      orionPx = toCanvas(a.x + t * (b.x - a.x), a.y + t * (b.y - a.y));
    }

    // Connect past path to Orion's actual position
    if (lastPastPt) {
      ctx.save();
      ctx.setLineDash([]);
      ctx.strokeStyle = "rgba(0,220,255,0.4)";
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(lastPastPt.x, lastPastPt.y);
      ctx.lineTo(orionPx.x, orionPx.y);
      ctx.stroke();
      ctx.restore();
    }

    // --- Earth distance label — directly below the "Orion" text ---
    const earthDistKm = telemetry?.earthDistKm ?? null;
    if (earthDistKm != null) {
      const distText = fmtDistCanvas(earthDistKm, unitRef.current);
      ctx.save();
      ctx.font = "bold 9px monospace";
      ctx.textAlign = "center";
      const textW = ctx.measureText(distText).width;
      ctx.fillStyle = "rgba(6,11,20,0.7)";
      ctx.fillRect(orionPx.x - textW / 2 - 3, orionPx.y + 20, textW + 6, 14);
      ctx.fillStyle = "rgba(0,255,136,0.85)";
      ctx.fillText(distText, orionPx.x, orionPx.y + 30);
      ctx.restore();
    }

    // --- Moon distance label (near the Moon) ---
    const moonDistKm = telemetry?.moonDistKm ?? null;
    if (moonDistKm != null) {
      const moonDistText = fmtDistCanvas(moonDistKm, unitRef.current);
      ctx.save();
      ctx.font = "8px monospace";
      ctx.fillStyle = "rgba(180,185,190,0.6)";
      ctx.textAlign = "center";
      ctx.fillText(moonDistText, moonPx.x, moonPx.y - moonR - 6);
      ctx.restore();
    }

    // Orion glow
    ctx.save();
    const orionGlow = ctx.createRadialGradient(orionPx.x, orionPx.y, 0, orionPx.x, orionPx.y, 14);
    orionGlow.addColorStop(0, "rgba(0,255,136,0.55)");
    orionGlow.addColorStop(1, "rgba(0,255,136,0)");
    ctx.beginPath();
    ctx.arc(orionPx.x, orionPx.y, 14, 0, Math.PI * 2);
    ctx.fillStyle = orionGlow;
    ctx.fill();
    ctx.restore();

    // Orion dot
    ctx.save();
    ctx.beginPath();
    ctx.arc(orionPx.x, orionPx.y, 4, 0, Math.PI * 2);
    ctx.fillStyle = "#00ff88";
    ctx.fill();
    ctx.restore();

    // Orion label — directly below the dot, centered, so it follows the dot.
    ctx.save();
    ctx.font = "bold 9px monospace";
    ctx.fillStyle = "#00ff88";
    ctx.textAlign = "center";
    ctx.fillText("Orion", orionPx.x, orionPx.y + 14);
    ctx.restore();

    // Ground track — show what region Orion is above.
    // When inside the Moon's SOI (~61,500 km), show lunar features instead.
    if (stateVector && (stateVector.position.x !== 0 || stateVector.position.y !== 0)) {
      const LUNAR_SOI_KM = 61500;
      const inLunarSoi = telemetry && telemetry.moonDistKm < LUNAR_SOI_KM && moonPosition;
      const trackLabel = inLunarSoi && moonPosition
        ? getLunarGroundTrackLabel(
            {
              x: stateVector.position.x - moonPosition.x,
              y: stateVector.position.y - moonPosition.y,
              z: stateVector.position.z - moonPosition.z,
            },
            moonPosition,
          )
        : getGroundTrackLabel(stateVector.position, metMs);
      ctx.save();
      ctx.font = "8px monospace";
      ctx.fillStyle = inLunarSoi ? "rgba(200, 200, 220, 0.6)" : "rgba(0, 255, 136, 0.5)";
      ctx.textAlign = "left";
      ctx.textAlign = "center";
      ctx.fillText(trackLabel, orionPx.x, orionPx.y + 46);
      ctx.restore();
    }

    // --- Moon detail inset ---
    // Uses REAL spacecraft position relative to Moon (stateVector - moonPosition),
    // projected onto a 2D frame aligned with the Earth-Moon axis so the inset
    // reads the same orientation as the main view (Earth left, far side right).
    const inset = insetRef.current;
    if (showInset && inset && stateVector && moonPosition && telemetry) {
      const iw = inset.clientWidth;
      const ih = inset.clientHeight;
      if (iw > 0 && ih > 0) {
        if (inset.width !== iw * dpr || inset.height !== ih * dpr) {
          inset.width = iw * dpr;
          inset.height = ih * dpr;
        }
        const ictx = inset.getContext("2d");
        if (ictx) {
          ictx.setTransform(dpr, 0, 0, dpr, 0, 0);
          ictx.clearRect(0, 0, iw, ih);

          // Background
          ictx.fillStyle = "#060b14";
          ictx.fillRect(0, 0, iw, ih);

          // Dynamic zoom: viewport scales with Moon distance so Orion is
          // always visible with ~30% padding. Clamps between 20,000 km
          // (tight flyby view) and 130,000 km (initial approach view).
          const moonDistKm = telemetry.moonDistKm;
          const viewKm = Math.max(20000, Math.min(130000, moonDistKm * 2.6));
          const moonCx = iw / 2;
          const moonCy = ih / 2;
          const insetPxPerKm = Math.min(iw, ih) / viewKm;

          // --- Real position projection ---
          // Earth is at J2000 origin, so moonPosition IS the Earth→Moon vector.
          // Build an orthonormal 2D frame in the orbital plane:
          //   u_hat = unit vector along Earth→Moon (so +X points away from Earth)
          //   v_hat = perpendicular in the ecliptic XY plane
          const mx = moonPosition.x;
          const my = moonPosition.y;
          const moonMag = Math.hypot(mx, my);
          const ux = moonMag > 0 ? mx / moonMag : 1;
          const uy = moonMag > 0 ? my / moonMag : 0;
          // 90° rotation in the ecliptic plane (right-handed, Z up)
          const vx = -uy;
          const vy = ux;

          // Orion relative to Moon in J2000 km
          const drx = stateVector.position.x - mx;
          const dry = stateVector.position.y - my;
          // Project onto (u_hat, v_hat). relX = "along Earth-Moon axis",
          // relY = "perpendicular in orbital plane".
          const relX = drx * ux + dry * uy;
          const relY = drx * vx + dry * vy;

          // Append to trail when we've moved enough or metMs advanced.
          const trail = insetTrailRef.current;
          const last = trail[trail.length - 1];
          if (!last || Math.hypot(relX - last.relX, relY - last.relY) > 200 || metMs - last.metMs > 60000) {
            trail.push({ relX, relY, metMs });
            // Trim to the last 120 points (keeps the trail short and relevant)
            if (trail.length > 120) trail.shift();
          }

          // Gravity rings at various Moon-centered distances
          const innerRings = [5000, 10000, 20000];
          for (const rKm of innerRings) {
            const rPx = rKm * insetPxPerKm;
            if (rPx < 2 || rPx > Math.max(iw, ih)) continue;
            ictx.save();
            ictx.beginPath();
            ictx.arc(moonCx, moonCy, rPx, 0, Math.PI * 2);
            ictx.strokeStyle = "rgba(180, 190, 210, 0.13)";
            ictx.lineWidth = 0.5;
            ictx.setLineDash([3, 4]);
            ictx.stroke();
            ictx.restore();
          }

          // Direction indicator: arrow pointing toward Earth (negative u_hat)
          ictx.save();
          ictx.strokeStyle = "rgba(100,160,255,0.4)";
          ictx.fillStyle = "rgba(100,160,255,0.4)";
          ictx.lineWidth = 1;
          ictx.beginPath();
          ictx.moveTo(14, ih - 14);
          ictx.lineTo(30, ih - 14);
          ictx.stroke();
          ictx.beginPath();
          ictx.moveTo(14, ih - 14);
          ictx.lineTo(18, ih - 17);
          ictx.lineTo(18, ih - 11);
          ictx.closePath();
          ictx.fill();
          ictx.font = "7px monospace";
          ictx.fillStyle = "rgba(100,160,255,0.55)";
          ictx.textAlign = "left";
          ictx.fillText("to Earth", 33, ih - 11);
          ictx.restore();

          // Real trail — actual JPL positions transformed to Moon-relative frame
          if (trail.length >= 2) {
            ictx.save();
            ictx.setLineDash([]);
            ictx.lineWidth = 1.3;
            ictx.strokeStyle = "rgba(0,220,255,0.55)";
            ictx.beginPath();
            for (let i = 0; i < trail.length; i++) {
              const px = moonCx + trail[i].relX * insetPxPerKm;
              const py = moonCy - trail[i].relY * insetPxPerKm; // canvas Y flipped
              if (i === 0) ictx.moveTo(px, py);
              else ictx.lineTo(px, py);
            }
            ictx.stroke();
            ictx.restore();
          }

          // Moon
          const moonR = Math.max(14, Math.min(iw, ih) * 0.11);
          const mGrad = ictx.createRadialGradient(
            moonCx - moonR * 0.3, moonCy - moonR * 0.3, 0,
            moonCx, moonCy, moonR
          );
          mGrad.addColorStop(0, "#e8ecef");
          mGrad.addColorStop(0.6, "#9aa0a4");
          mGrad.addColorStop(1, "#3a3e42");
          ictx.save();
          ictx.beginPath();
          ictx.arc(moonCx, moonCy, moonR, 0, Math.PI * 2);
          ictx.fillStyle = mGrad;
          ictx.fill();
          ictx.fillStyle = "rgba(0,0,0,0.2)";
          ictx.beginPath();
          ictx.arc(moonCx - moonR * 0.3, moonCy - moonR * 0.2, moonR * 0.12, 0, Math.PI * 2);
          ictx.fill();
          ictx.beginPath();
          ictx.arc(moonCx + moonR * 0.2, moonCy + moonR * 0.3, moonR * 0.08, 0, Math.PI * 2);
          ictx.fill();
          ictx.restore();

          ictx.save();
          ictx.font = "bold 10px monospace";
          ictx.fillStyle = "rgba(180,185,190,0.9)";
          ictx.textAlign = "center";
          ictx.fillText("Moon", moonCx, moonCy + moonR + 12);
          ictx.restore();

          // Orion at its real relative position
          const orionIx = moonCx + relX * insetPxPerKm;
          const orionIy = moonCy - relY * insetPxPerKm; // canvas Y flipped

          if (orionIx > -10 && orionIx < iw + 10 && orionIy > -10 && orionIy < ih + 10) {
            ictx.save();
            const glow = ictx.createRadialGradient(orionIx, orionIy, 0, orionIx, orionIy, 12);
            glow.addColorStop(0, "rgba(0,255,136,0.6)");
            glow.addColorStop(1, "rgba(0,255,136,0)");
            ictx.beginPath();
            ictx.arc(orionIx, orionIy, 12, 0, Math.PI * 2);
            ictx.fillStyle = glow;
            ictx.fill();
            ictx.beginPath();
            ictx.arc(orionIx, orionIy, 4, 0, Math.PI * 2);
            ictx.fillStyle = "#00ff88";
            ictx.fill();
            ictx.font = "bold 10px monospace";
            ictx.fillStyle = "#00ff88";
            ictx.textAlign = "left";
            ictx.fillText("Orion", orionIx + 7, orionIy - 7);
            ictx.font = "9px monospace";
            ictx.fillStyle = "rgba(0,255,136,0.75)";
            ictx.fillText(fmtDistCanvas(telemetry.moonDistKm, unitRef.current), orionIx + 7, orionIy + 6);
            // Lunar ground track label
            if (moonPosition) {
              const lunarLabel = getLunarGroundTrackLabel(
                { x: stateVector.position.x - moonPosition.x, y: stateVector.position.y - moonPosition.y, z: stateVector.position.z - moonPosition.z },
                moonPosition,
              );
              ictx.font = "7px monospace";
              ictx.fillStyle = "rgba(200,200,220,0.6)";
              ictx.fillText(lunarLabel, orionIx + 7, orionIy + 16);
            }
            ictx.restore();
          } else {
            // Orion is outside the viewport — draw an off-screen indicator
            // pointing toward it from the center.
            const ang = Math.atan2(orionIy - moonCy, orionIx - moonCx);
            const edgeR = Math.min(iw, ih) / 2 - 18;
            const ex = moonCx + Math.cos(ang) * edgeR;
            const ey = moonCy + Math.sin(ang) * edgeR;
            ictx.save();
            ictx.translate(ex, ey);
            ictx.rotate(ang);
            ictx.fillStyle = "rgba(0,255,136,0.85)";
            ictx.beginPath();
            ictx.moveTo(0, 0);
            ictx.lineTo(-10, -5);
            ictx.lineTo(-10, 5);
            ictx.closePath();
            ictx.fill();
            ictx.restore();
            ictx.save();
            ictx.font = "8px monospace";
            ictx.fillStyle = "rgba(0,255,136,0.7)";
            ictx.textAlign = "center";
            ictx.fillText(
              `Orion · ${fmtDistCanvas(telemetry.moonDistKm, unitRef.current)}`,
              moonCx,
              moonCy + Math.min(iw, ih) / 2 - 4,
            );
            ictx.restore();
          }

          // Inset title
          ictx.save();
          ictx.font = "bold 9px monospace";
          ictx.fillStyle = "rgba(0,229,255,0.75)";
          ictx.textAlign = "left";
          ictx.fillText(insetLabelsRef.current.moonDetail, 10, 14);
          ictx.font = "8px monospace";
          ictx.fillStyle = "rgba(160,184,207,0.65)";
          {
            const viewLabel = unitRef.current === "mph"
              ? `${Math.round(viewKm * 0.621371).toLocaleString()} mi view`
              : unitRef.current === "kn"
              ? `${Math.round(viewKm * 0.539957).toLocaleString()} nmi view`
              : `${viewKm.toLocaleString()} ${insetLabelsRef.current.kmView}`;
            ictx.fillText(viewLabel, 10, 25);
          }
          ictx.restore();
        }
      }
    }
    // --- Earth detail inset ---
    // Shows Orion's position relative to Earth during re-entry approach.
    // Mirrors the Moon inset pattern but centered on Earth.
    const earthInset = earthInsetRef.current;
    if (showEarthInset && earthInset && stateVector && telemetry) {
      const eiw = earthInset.clientWidth;
      const eih = earthInset.clientHeight;
      if (eiw > 0 && eih > 0) {
        if (earthInset.width !== eiw * dpr || earthInset.height !== eih * dpr) {
          earthInset.width = eiw * dpr;
          earthInset.height = eih * dpr;
        }
        const ectx = earthInset.getContext("2d");
        if (ectx) {
          ectx.setTransform(dpr, 0, 0, dpr, 0, 0);
          ectx.clearRect(0, 0, eiw, eih);

          // Background
          ectx.fillStyle = "#060b14";
          ectx.fillRect(0, 0, eiw, eih);

          // Dynamic zoom — scale with Earth distance
          const earthDistKm = telemetry.earthDistKm;
          const eViewKm = Math.max(20000, Math.min(130000, earthDistKm * 2.6));
          const earthCx = eiw / 2;
          const earthCy = eih / 2;
          const ePxPerKm = Math.min(eiw, eih) / eViewKm;

          // Altitude rings
          const altRings = [10000, 20000, 40000];
          for (const rKm of altRings) {
            const rPx = (6371 + rKm) * ePxPerKm;
            if (rPx < 2 || rPx > Math.max(eiw, eih)) continue;
            ectx.save();
            ectx.beginPath();
            ectx.arc(earthCx, earthCy, rPx, 0, Math.PI * 2);
            ectx.strokeStyle = "rgba(100,160,255,0.12)";
            ectx.lineWidth = 0.5;
            ectx.setLineDash([3, 4]);
            ectx.stroke();
            ectx.restore();
          }

          // Earth
          const eR = Math.max(8, 6371 * ePxPerKm);
          const eGrad = ectx.createRadialGradient(
            earthCx - eR * 0.3, earthCy - eR * 0.3, 0,
            earthCx, earthCy, eR
          );
          eGrad.addColorStop(0, "#4a90d9");
          eGrad.addColorStop(0.6, "#1a5a9e");
          eGrad.addColorStop(1, "#0a2a4e");
          ectx.save();
          ectx.beginPath();
          ectx.arc(earthCx, earthCy, eR, 0, Math.PI * 2);
          ectx.fillStyle = eGrad;
          ectx.fill();
          ectx.restore();

          ectx.save();
          ectx.font = "bold 10px monospace";
          ectx.fillStyle = "rgba(100,160,255,0.9)";
          ectx.textAlign = "center";
          ectx.fillText("Earth", earthCx, earthCy + eR + 12);
          ectx.restore();

          // Splashdown zone marker (~25°N, 120°W in the Pacific)
          // Draw as a small orange crosshair near Earth
          if (eR > 5) {
            const splashAngle = Math.PI * 0.7; // approximate position on globe
            const splashR = eR * 0.8;
            const sx = earthCx + Math.cos(splashAngle) * splashR;
            const sy = earthCy + Math.sin(splashAngle) * splashR;
            ectx.save();
            ectx.beginPath();
            ectx.arc(sx, sy, 3, 0, Math.PI * 2);
            ectx.strokeStyle = "rgba(255,140,0,0.7)";
            ectx.lineWidth = 1;
            ectx.setLineDash([2, 2]);
            ectx.stroke();
            ectx.font = "6px monospace";
            ectx.fillStyle = "rgba(255,140,0,0.6)";
            ectx.textAlign = "center";
            ectx.fillText("SPLASHDOWN", sx, sy + 8);
            ectx.restore();
          }

          // Earth trail
          const eTrail = earthInsetTrailRef.current;
          const orionR = Math.sqrt(
            stateVector.position.x ** 2 + stateVector.position.y ** 2 + stateVector.position.z ** 2
          );
          // Project onto a simple 2D plane — use X and Y from the state vector
          // normalized by Earth distance, centered on Earth
          const orionEIx = earthCx + stateVector.position.x / orionR * earthDistKm * ePxPerKm;
          const orionEIy = earthCy - stateVector.position.y / orionR * earthDistKm * ePxPerKm;

          // Actually, simpler: Orion is at earthDistKm from Earth center.
          // Use RA to determine the angle, place Orion at that angle at the right distance.
          const ra = Math.atan2(stateVector.position.y, stateVector.position.x);
          const dec = Math.asin(stateVector.position.z / orionR);
          // Project: angle in the 2D plane = RA, distance from center = earthDistKm (projected by cos(dec))
          const projDist = earthDistKm * Math.cos(dec) * ePxPerKm;
          const oEIx = earthCx + Math.cos(ra) * projDist;
          const oEIy = earthCy - Math.sin(ra) * projDist;

          // Append to trail
          const lastE = eTrail[eTrail.length - 1];
          if (!lastE || Math.hypot(oEIx - lastE.x, oEIy - lastE.y) > 2 || metMs - lastE.metMs > 60000) {
            eTrail.push({ x: oEIx, y: oEIy, metMs });
            if (eTrail.length > 120) eTrail.shift();
          }

          // Draw trail
          if (eTrail.length >= 2) {
            ectx.save();
            ectx.strokeStyle = "rgba(0,220,255,0.5)";
            ectx.lineWidth = 1.3;
            ectx.beginPath();
            for (let i = 0; i < eTrail.length; i++) {
              if (i === 0) ectx.moveTo(eTrail[i].x, eTrail[i].y);
              else ectx.lineTo(eTrail[i].x, eTrail[i].y);
            }
            ectx.stroke();
            ectx.restore();
          }

          // Orion dot
          if (oEIx > -10 && oEIx < eiw + 10 && oEIy > -10 && oEIy < eih + 10) {
            ectx.save();
            const glow = ectx.createRadialGradient(oEIx, oEIy, 0, oEIx, oEIy, 12);
            glow.addColorStop(0, "rgba(0,255,136,0.6)");
            glow.addColorStop(1, "rgba(0,255,136,0)");
            ectx.beginPath();
            ectx.arc(oEIx, oEIy, 12, 0, Math.PI * 2);
            ectx.fillStyle = glow;
            ectx.fill();
            ectx.beginPath();
            ectx.arc(oEIx, oEIy, 4, 0, Math.PI * 2);
            ectx.fillStyle = "#00ff88";
            ectx.fill();
            ectx.font = "bold 10px monospace";
            ectx.fillStyle = "#00ff88";
            ectx.textAlign = "left";
            ectx.fillText("Orion", oEIx + 7, oEIy - 7);
            ectx.font = "9px monospace";
            ectx.fillStyle = "rgba(0,255,136,0.75)";
            ectx.fillText(fmtDistCanvas(earthDistKm, unitRef.current), oEIx + 7, oEIy + 6);
            // Ground track label
            const groundLabel = getGroundTrackLabel(stateVector.position, metMs);
            ectx.font = "7px monospace";
            ectx.fillStyle = "rgba(0,255,136,0.5)";
            ectx.fillText(groundLabel, oEIx + 7, oEIy + 16);
            ectx.restore();
          } else {
            // Off-screen indicator
            const ang = Math.atan2(oEIy - earthCy, oEIx - earthCx);
            const edgeR = Math.min(eiw, eih) / 2 - 18;
            const ex = earthCx + Math.cos(ang) * edgeR;
            const ey = earthCy + Math.sin(ang) * edgeR;
            ectx.save();
            ectx.translate(ex, ey);
            ectx.rotate(ang);
            ectx.fillStyle = "rgba(0,255,136,0.85)";
            ectx.beginPath();
            ectx.moveTo(0, 0);
            ectx.lineTo(-10, -5);
            ectx.lineTo(-10, 5);
            ectx.closePath();
            ectx.fill();
            ectx.restore();
            ectx.save();
            ectx.font = "8px monospace";
            ectx.fillStyle = "rgba(0,255,136,0.7)";
            ectx.textAlign = "center";
            ectx.fillText(
              `Orion · ${fmtDistCanvas(earthDistKm, unitRef.current)}`,
              earthCx, earthCy + Math.min(eiw, eih) / 2 - 4,
            );
            ectx.restore();
          }

          // Direction indicator: arrow pointing toward Moon (right side)
          ectx.save();
          ectx.strokeStyle = "rgba(180,185,190,0.4)";
          ectx.fillStyle = "rgba(180,185,190,0.4)";
          ectx.lineWidth = 1;
          ectx.beginPath();
          ectx.moveTo(eiw - 30, eih - 14);
          ectx.lineTo(eiw - 14, eih - 14);
          ectx.stroke();
          ectx.beginPath();
          ectx.moveTo(eiw - 14, eih - 14);
          ectx.lineTo(eiw - 18, eih - 17);
          ectx.lineTo(eiw - 18, eih - 11);
          ectx.closePath();
          ectx.fill();
          ectx.font = "7px monospace";
          ectx.fillStyle = "rgba(180,185,190,0.55)";
          ectx.textAlign = "right";
          ectx.fillText("to Moon", eiw - 33, eih - 11);
          ectx.restore();

          // Inset title
          ectx.save();
          ectx.font = "bold 9px monospace";
          ectx.fillStyle = "rgba(100,160,255,0.75)";
          ectx.textAlign = "left";
          ectx.fillText(insetLabelsRef.current.earthDetail, 10, 14);
          ectx.font = "8px monospace";
          ectx.fillStyle = "rgba(160,184,207,0.65)";
          {
            const viewLabel = unitRef.current === "mph"
              ? `${Math.round(eViewKm * 0.621371).toLocaleString()} mi view`
              : unitRef.current === "kn"
              ? `${Math.round(eViewKm * 0.539957).toLocaleString()} nmi view`
              : `${eViewKm.toLocaleString()} ${insetLabelsRef.current.kmView}`;
            ectx.fillText(viewLabel, 10, 25);
          }
          ectx.restore();
        }
      }
    }
  }, [stateVector, moonPosition, metMs, telemetry, showInset, showEarthInset, realScale]);

  // Animation loop
  useEffect(() => {
    let alive = true;

    function loop() {
      if (!alive) return;
      draw();
      rafRef.current = requestAnimationFrame(loop);
    }

    rafRef.current = requestAnimationFrame(loop);

    return () => {
      alive = false;
      if (rafRef.current !== null) {
        cancelAnimationFrame(rafRef.current);
        rafRef.current = null;
      }
    };
  }, [draw]);

  // Resize observer
  useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    const ro = new ResizeObserver(() => {
      draw();
    });
    ro.observe(container);

    return () => ro.disconnect();
  }, [draw]);

  // Compute accessible ground track description
  const LUNAR_SOI_KM = 61500;
  const inLunarSoi = telemetry && telemetry.moonDistKm < LUNAR_SOI_KM && moonPosition;
  const groundLabel =
    stateVector && (stateVector.position.x !== 0 || stateVector.position.y !== 0)
      ? (inLunarSoi && moonPosition
        ? getLunarGroundTrackLabel(
            { x: stateVector.position.x - moonPosition.x, y: stateVector.position.y - moonPosition.y, z: stateVector.position.z - moonPosition.z },
            moonPosition,
          )
        : getGroundTrackLabel(stateVector.position, metMs))
      : null;
  const orbitDescription = [
    "Lunar flyby trajectory map.",
    telemetry ? `Orion is ${fmtDistCanvas(telemetry.earthDistKm, speedUnit)} from Earth` : "",
    telemetry ? `and ${fmtDistCanvas(telemetry.moonDistKm, speedUnit)} from the Moon.` : "",
    groundLabel || "",
    metMs < 5 * 24 * 3600 * 1000 ? "Outbound trajectory." : "Return trajectory.",
  ].filter(Boolean).join(" ");

  return (
    <div style={isFullscreen ? {
      position: "fixed", top: 0, left: 0, right: 0, bottom: 0,
      zIndex: 9999, background: "#060b14",
    } : undefined}>
    <PanelFrame title={t("orbitMap.title")} accentColor="var(--accent-cyan)" headerRight={<span style={{ fontSize: "9px", color: "var(--text-muted)", letterSpacing: "1px" }}>{t("orbitMap.topDown").toUpperCase()}</span>}>
      <div
        ref={containerRef}
        style={{
          width: "100%",
          height: isFullscreen ? "calc(100vh - 36px)" : "min(320px, 50vw)",
          position: "relative",
          overflow: "hidden",
          borderRadius: isFullscreen ? 0 : 4,
        }}
      >
        <span className="sr-only">{orbitDescription}</span>
        <canvas
          ref={canvasRef}
          aria-hidden="true"
          style={{ display: "block", width: "100%", height: "100%" }}
        />

        {/* Moon detail inset canvas — always mounted so dimensions are valid.
            Uses min() so it shrinks on small phones instead of overflowing. */}
        <canvas
          ref={insetRef}
          aria-hidden="true"
          width={520}
          height={520}
          className="orbit-inset"
          style={{
            position: "absolute",
            bottom: 8,
            right: 8,
            border: "2px solid rgba(0,229,255,0.5)",
            borderRadius: 6,
            boxShadow: "0 4px 16px rgba(0,0,0,0.6)",
            background: "#060b14",
            opacity: showInset ? 1 : 0,
            pointerEvents: showInset ? "auto" : "none",
            transition: "opacity 200ms ease-out",
            zIndex: 10,
          }}
        />

        {/* Earth detail inset canvas */}
        <canvas
          ref={earthInsetRef}
          aria-hidden="true"
          width={520}
          height={520}
          className="orbit-inset"
          style={{
            position: "absolute",
            bottom: 8,
            left: 8,
            border: "2px solid rgba(100,160,255,0.5)",
            borderRadius: 6,
            boxShadow: "0 4px 16px rgba(0,0,0,0.6)",
            background: "#060b14",
            opacity: showEarthInset ? 1 : 0,
            pointerEvents: showEarthInset ? "auto" : "none",
            transition: "opacity 200ms ease-out",
            zIndex: 10,
          }}
        />

        {/* Moon detail toggle button */}
        <button
          onClick={() => setShowInset((v) => !v)}
          style={{
            position: "absolute",
            top: 8,
            right: 8,
            padding: "4px 10px",
            background: showInset ? "rgba(0,229,255,0.15)" : "rgba(6,11,20,0.8)",
            border: "1px solid rgba(0,229,255,0.3)",
            borderRadius: 4,
            color: "var(--accent-cyan)",
            fontSize: 9,
            fontWeight: 700,
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            fontFamily: "'JetBrains Mono', monospace",
            cursor: "pointer",
            zIndex: 11,
          }}
          aria-label={showInset ? "Hide Moon detail" : "Show Moon detail"}
        >
          🌙 {showInset ? "✕" : t("orbitMap.zoom")}
        </button>

        {/* Earth detail toggle button */}
        <button
          onClick={() => setShowEarthInset((v) => !v)}
          style={{
            position: "absolute",
            top: 8,
            right: showInset ? 80 : 70,
            padding: "4px 10px",
            background: showEarthInset ? "rgba(100,160,255,0.15)" : "rgba(6,11,20,0.8)",
            border: "1px solid rgba(100,160,255,0.3)",
            borderRadius: 4,
            color: "rgba(100,160,255,0.9)",
            fontSize: 9,
            fontWeight: 700,
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            fontFamily: "'JetBrains Mono', monospace",
            cursor: "pointer",
            zIndex: 11,
          }}
          aria-label={showEarthInset ? "Hide Earth detail" : "Show Earth detail"}
        >
          🌍 {showEarthInset ? "✕" : t("orbitMap.zoom")}
        </button>

        {/* Fullscreen toggle button */}
        <button
          onClick={() => setIsFullscreen((v) => !v)}
          style={{
            position: "absolute",
            top: 8,
            left: 8,
            padding: "4px 10px",
            background: isFullscreen ? "rgba(0,229,255,0.15)" : "rgba(6,11,20,0.8)",
            border: "1px solid rgba(0,229,255,0.3)",
            borderRadius: 4,
            color: "var(--accent-cyan)",
            fontSize: 9,
            fontWeight: 700,
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            fontFamily: "'JetBrains Mono', monospace",
            cursor: "pointer",
            zIndex: 11,
          }}
          aria-label={isFullscreen ? "Exit fullscreen" : "Enter fullscreen"}
        >
          {isFullscreen ? "✕ EXIT" : "⛶ FULL"}
        </button>

        {/* Real scale toggle */}
        <button
          onClick={() => setRealScale((v) => !v)}
          style={{
            position: "absolute",
            top: 8,
            left: 80,
            padding: "4px 10px",
            background: realScale ? "rgba(0,229,255,0.15)" : "rgba(6,11,20,0.8)",
            border: "1px solid rgba(0,229,255,0.3)",
            borderRadius: 4,
            color: "var(--accent-cyan)",
            fontSize: 9,
            fontWeight: 700,
            letterSpacing: "0.1em",
            textTransform: "uppercase",
            fontFamily: "'JetBrains Mono', monospace",
            cursor: "pointer",
            zIndex: 11,
          }}
          aria-label={realScale ? "Show exaggerated scale" : "Show real scale"}
        >
          ⊕ SCALE
        </button>
      </div>
    </PanelFrame>
    </div>
  );
}
